### ISSUE TITLE
This starter is not serving the App *Not Found*

### ISSUE THREAD

**Issue by ivanjeremic** [lit/lit-element-starter-js#18]
This starter is not serving the App when running `npm run serve` I get in Browser *Not Found* (No console errors).

I tried to get more info with `npm test` but all I get is 

```
Chromium: |██████████████████████████████| 1/1 test files | 0 passed, 0 failed
Firefox:  |██████████████████████████████| 1/1 test files | 0 passed, 0 failed
Webkit:   |██████████████████████████████| 1/1 test files | 0 passed, 0 failed

Error while running tests.

npm ERR! code 1
npm ERR! path /home/inux/lit-browser-extension
npm ERR! command failed
npm ERR! command sh -c wtr
```

I'm on Windows WSL and projects created with open-wc work just fine.

**Comment by AndrewJakubowicz** [comment]
Hi thanks for the issue and sorry for the slow response. This should be addressed after [this change](https://github.com/lit/lit/commit/8b9dcb4d10e4161083146ae40d0b12174a63d31d) is released.

**Comment by AndrewJakubowicz** [comment]
Sorry for the slow turnaround. Could you try and reproduce this issue again now that https://github.com/lit/lit-element-starter-js/commit/af17a326a09360760b297c395b3bc1a54f1cebf5 has been merged. Let me know if that change resolves the issue.

Thank you!

**Comment by AndrewJakubowicz** [comment]
Closing as this should be resolved. Please re-open or file a new issue if this problem persists. Thank you!
